name: Create Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    - name: Check zig version
      run: zig version
    - name: Build
      run: zig build
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zig-out/bin/get-weather
        asset_name: get-weather-linux-amd64
        tag: ${{ github.ref }}
